version: '3.8'

services:
  wikimedia-eu-stream:
    image: ferpinan/wikimedia-eu-stream:latest
    container_name: wikimedia-eu-stream
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ferpinan-network
    restart: unless-stopped

networks:
  ferpinan-network:
    external: true