spring:
  application:
    name: wikimedia-eu-stream
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: wikimedia-eu-stream
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
wikimedia:
  lang-wiki-id: euwiki
  source-topic: wikimedia.recentchange
  sink-topic: wikimedia.recentchange.eu